###
# @name createAsset
POST http://localhost:3000/assets
Content-Type: application/json

{
  "name": "Amazon 10",
  "symbol": "AWS00",
  "price": "100",
  "image": "AMZN.png"
}
###
@assetId = {{createAsset.response.body._id}}


###
GET http://localhost:3000/assets/AWS1

###
GET http://localhost:3000/assets


###
# @name createWallet
POST http://localhost:3000/wallets

###
@walletId = {{createWallet.response.body._id}}

###
GET http://localhost:3000/wallets

###
GET http://localhost:3000/wallets/{{ walletId }}

###
POST http://localhost:3000/wallets/{{ walletId }}/assets
Content-Type: application/json

{
  "assetId": "{{assetId}}",
  "shares": 100
}